CREATE TABLE IF NOT EXISTS ai_agent_run_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  run_id VARCHAR(128) NOT NULL,
  user_id BIGINT NOT NULL,
  conversation_id VARCHAR(128) NOT NULL,
  intent VARCHAR(64) NOT NULL DEFAULT 'unknown',
  status VARCHAR(32) NOT NULL,
  duration_ms BIGINT NULL,
  model_mode VARCHAR(128) NOT NULL DEFAULT 'unknown',
  next_action VARCHAR(64) NULL,
  node_timings_json JSON NOT NULL,
  selected_tools_json JSON NOT NULL,
  tool_errors_json JSON NOT NULL,
  degradation_modes_json JSON NOT NULL,
  plan_saved TINYINT(1) NOT NULL DEFAULT 0,
  error_code VARCHAR(64) NULL,
  error_message VARCHAR(512) NULL,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_ai_agent_run_id (run_id),
  KEY idx_ai_agent_run_time (create_time),
  KEY idx_ai_agent_run_user_time (user_id, create_time),
  KEY idx_ai_agent_run_intent_status (intent, status, create_time),
  KEY idx_ai_agent_run_conversation (conversation_id, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
