-- Conversation summaries were refreshed with LocalDateTime.now() while the
-- production JVM used UTC. Message timestamps are generated by MySQL in the
-- Asia/Shanghai business timezone, leaving update_time exactly eight hours
-- behind the latest message. Repair only rows that match that historical
-- signature so correctly stored rows are not shifted.
UPDATE ai_conversation AS conversation
JOIN (
    SELECT ai_conversation_id, MAX(create_time) AS latest_message_time
    FROM ai_message
    GROUP BY ai_conversation_id
) AS message_summary
    ON message_summary.ai_conversation_id = conversation.id
SET conversation.update_time = message_summary.latest_message_time
WHERE TIMESTAMPDIFF(
          SECOND,
          conversation.update_time,
          message_summary.latest_message_time
      ) BETWEEN 28790 AND 28810;
